#                             Numpy

`The foundation library for numerical computing in Python. Its core feature is the array — a fast, memory-efficient way to store and do math on large sets of numbers all at once, instead of looping through them one by one. Think of it as Python's engine for "do this calculation on a whole table of numbers instantly.`

NumPy handles the raw numbers

In [5]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)
print("Setup working ✅")

NumPy version: 2.5.1
Pandas version: 3.0.5
Setup working ✅


## 1. Arrays - the core concept

NumPy's whole point is the ndarray (n-dimensional array) - faster and more memory-efficient than Python lists because it stores data in one contiguous block of the same type.

`shape, ndim, dtype, size`

In [15]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2],[3,4]]) # D= r*c

print("array 1 :", arr1)
print("array 2 :", arr2)

print("shape of array 1 :", arr1.shape)
print("shape of array 2 :", arr2.shape)

print("N-dimensions of array 1 :", arr1.ndim)
print("N-dimensions of array 2 :", arr2.ndim)

print("Data-Type of array 1 :", arr1.dtype)
print("Data-Type of array 2 :", arr2.dtype)

print("size of array 1 :", arr1.size)
print("size of array 2 :", arr2.size)



array 1 : [1 2 3 4]
array 2 : [[1 2]
 [3 4]]
shape of array 1 : (4,)
shape of array 2 : (2, 2)
N-dimensions of array 1 : 1
N-dimensions of array 2 : 2
Data-Type of array 1 : int64
Data-Type of array 2 : int64
size of array 1 : 4
size of array 2 : 4


## 2. Creating arrays (common shortcuts)

In [ ]:
a = np.zeros((4,4))
print("creating matrix 4*4 with all 0 elements : \n" , a)

b= np.ones((2,5))
print(" \n creating matrix 2*5 with all 1 elements : \n" , b)

c = np.arange(0,10,2) # (start,stop,step) : working with steppings 
print("\n starting with 0 ,ending at 10(exclude), stepping is 2 : ", c )

d = np.linspace(0,1,5)
print("\n  start from 0  , end at 1 , stepping 5 means there should different/space of 5 : ", d )



creating matrix 4*4 with all 0 elements : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
 creating matrix 2*5 with all 1 elements : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 starting with 0 ,ending at 10(exclude), stepping is 2 :  [0 2 4 6 8]

  start from 0  , end at 1 , stepping 5 means there should different/space of 5  [0.   0.25 0.5  0.75 1.  ]


## 3. Indexing & slicing

In [38]:
ab = np.array([1,3,5,7,9,11,13,15])

print("check element at first(0) index  .....>", ab[0])
print("check element at last(-1) index .....>", ab[-1])
print("check elements from 1st-3rd index .....>", ab[1:3])
print("check all-elements from back-reverse .....>", ab[::-1])

# 2D INDEXING
az = np.array([[2,4,6,8],[10,12,14,16]])

print("\n check element at 1st row with 2nd element : ", az[1,2])



check element at first(0) index  .....> 1
check element at last(-1) index .....> 15
check elements from 1st-3rd index .....> [3 5]
check all-elements from back-reverse .....> [15 13 11  9  7  5  3  1]

 check element at 1st row with 2nd element :  14
