#                             Numpy

`The foundation library for numerical computing in Python. Its core feature is the array — a fast, memory-efficient way to store and do math on large sets of numbers all at once, instead of looping through them one by one. Think of it as Python's engine for "do this calculation on a whole table of numbers instantly.`

NumPy handles the raw numbers

In [5]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)
print("Setup working ✅")

NumPy version: 2.5.1
Pandas version: 3.0.5
Setup working ✅


## 1. Arrays - the core concept

NumPy's whole point is the ndarray (n-dimensional array) - faster and more memory-efficient than Python lists because it stores data in one contiguous block of the same type.

`shape, ndim, dtype, size`

In [2]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2],[3,4]]) # D= r*c

print("array 1 :", arr1)
print("array 2 :", arr2)

print("shape of array 1 :", arr1.shape)
print("shape of array 2 :", arr2.shape)

print("N-dimensions of array 1 :", arr1.ndim)
print("N-dimensions of array 2 :", arr2.ndim)

print("Data-Type of array 1 :", arr1.dtype)
print("Data-Type of array 2 :", arr2.dtype)

print("size of array 1 :", arr1.size)
print("size of array 2 :", arr2.size)



array 1 : [1 2 3 4]
array 2 : [[1 2]
 [3 4]]
shape of array 1 : (4,)
shape of array 2 : (2, 2)
N-dimensions of array 1 : 1
N-dimensions of array 2 : 2
Data-Type of array 1 : int64
Data-Type of array 2 : int64
size of array 1 : 4
size of array 2 : 4


## 2. Creating arrays (common shortcuts)

In [24]:
a = np.zeros((4,4))
print("creating matrix 4*4 with all 0 elements : \n" , a)

b= np.ones((2,5))
print(" \n creating matrix 2*5 with all 1 elements : \n" , b)

c = np.arange(0,10,2) # (start,stop,step) : working with steppings 
print("\n starting with 0 ,ending at 10(exclude), stepping is 2 : ", c )

d = np.linspace(0,1,5)
print("\n  start from 0  , end at 1 , stepping 5 means there should different/space of 5 : ", d )

id = np.eye(2,2)
print(" \n make an identity matrix : \n ",id)

# Creates a 3x3 identity matrix with 1s on the diagonal
diagonal = np.diag([1, 1, 1])
print("\n set the diagonal elements :\n", diagonal)

creating matrix 4*4 with all 0 elements : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
 creating matrix 2*5 with all 1 elements : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 starting with 0 ,ending at 10(exclude), stepping is 2 :  [0 2 4 6 8]

  start from 0  , end at 1 , stepping 5 means there should different/space of 5 :  [0.   0.25 0.5  0.75 1.  ]
 
 make an identity matrix : 
  [[1. 0.]
 [0. 1.]]

 set the diagonal elements :
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


## 3. Indexing & slicing

In [4]:
ab = np.array([1,3,5,7,9,11,13,15])

print("check element at first(0) index  .....>", ab[0])
print("check element at last(-1) index .....>", ab[-1])
print("check elements from 1st-3rd index .....>", ab[1:3])
print("check all-elements from back-reverse .....>", ab[::-1])

# 2D INDEXING
az = np.array([[2,4,6,8],[10,12,14,16]])

print("\n check element at 1st row with 2nd element : ", az[1,2])
print("\n check each rows first element             : ", az[ :,0]) ## all rows, col 0 → [2,10]
print("\n check each first cols each element        : ", az[0,:]) ## all col, row 0 → [2,4,6,8]



check element at first(0) index  .....> 1
check element at last(-1) index .....> 15
check elements from 1st-3rd index .....> [3 5]
check all-elements from back-reverse .....> [15 13 11  9  7  5  3  1]

 check element at 1st row with 2nd element :  14

 check each rows first element             :  [ 2 10]

 check each first cols each element        :  [2 4 6 8]


### Important practice question.

In [5]:
p_q = np.array([5,12,8,10,20,3])
print("\n check which elements are greater than 10 : " , p_q[p_q >10]) # 
p_q[p_q >= 10]=0

print(p_q)


 check which elements are greater than 10 :  [12 20]
[5 0 8 0 0 3]


## 4. Numerical operations & vectorization

`This is NumPy's superpower — operations apply to the whole array at once, no loops:`

`"why is NumPy faster than a Python loop?" → vectorized operations run in optimized C code under the hood, not the Python interpreter.` 

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("\n add both arrays a+b   :" , a+b)
print("\n multiply both arrays  :" ,a*b)
print("\n make a square of a**b :" ,a**b)
print("\n check which elements are greater (boolean answer) :", a>1)


 add both arrays a+b   : [11 22 33]

 multiply both arrays  : [10 40 90]

 make a square of a**b : [              1         1048576 205891132094649]

 check which elements are greater (boolean answer: [False  True  True]


## 5. Basic statistics 

In [ ]:
sts = np.array([2,4,6,10,12,22,12])

print("Mean(Sum of all elements divided by count) sum/7 :", np.mean(sts))
print("Median:", np.median(sts))
print("Std Dev:", np.std(sts))
print("Min:", np.min(sts))
print("Max:", np.max(sts))
print("Sum:", np.sum(sts))

Mean: 9.714285714285714
Median: 10.0
Std Dev: 6.180945043652553
Min: 2
Max: 22
Sum: 68


## 6. Reshaping — comes up in ML preprocessing constantly

In [19]:
arr3 = np.arange(12)
reshaped = arr3.reshape(3,4)
print("Reshape gives shape to matrix 3*4 : \n ",reshaped )

flat = reshaped.flatten()
print(" \n flatten reverse the reshaped version :\n",flat)

Reshape gives shape to matrix 3*4 : 
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
 flatten reverse the reshaped version :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 7. Broadcasting (important )

NumPy lets you do math between arrays of different shapes without manually looping:

In [20]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10, 20, 30])

print(matrix + vector)   # vector added to every row

[[11 22 33]
 [14 25 36]]


Exercise : Practice Questions

In [23]:
# Multi-Dimensioanl Array
# [Layer,Row,Col] 
import numpy as np
abc = np.array([[["a","b","c","d"],["e","f","g","h"]],[["i","j","k","l"],["m","n","o","p"]]]) # layer: 0,1,2...

print(abc)
print(f" \n check number of dimensions: {abc.ndim}D")

khan =abc[1,0,0] #  we are exact i with using indexing 
print(f" \n check specific element at specific [layer,row ,col] : {khan}")

alex = abc[1,0,0] + abc[0,1,2] + abc[1,0,2]
print(f"\n lets concatenate the specific elements: {alex}")

[[['a' 'b' 'c' 'd']
  ['e' 'f' 'g' 'h']]

 [['i' 'j' 'k' 'l']
  ['m' 'n' 'o' 'p']]]
 
 check number of dimensions: 3D
 
 check specific element at specific [layer,row ,col] : i

 lets concatenate the specific elements: igk


In [39]:
# Slicing 
# subsequent : [start: end(exclude) : step]
ax = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

ab = ax[0:3:3] # [::select all] ,[-1 select all from reverse] , 
print(f"\n check the sliced part : {ab}\n")

cd = ax[::-1]
print("get all from reverse [::-1] :\n ", cd)

ss = ax[::-2] 
print("\n get all from 2nd reverse with step 2 : \n ", ss)

pp = ax[:,0] 
print("\n check all rows but give their first(0) element  ",pp)

ps = ax[:,0:3] 
print("\n from all rows , slice 1st-4th col :\n",ps)

pq = ax[:,1:3]  
print("\n from all rows , slice 1st-4th col :\n",pq)


 check the sliced part : [[1 2 3 4]]

get all from reverse [::-1] :
  [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

 get all from 2nd reverse with step 2 : 
  [[13 14 15 16]
 [ 5  6  7  8]]

 check all rows but give their first(0) element   [ 1  5  9 13]

 from all rows , slice 1st-4th col :
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]

 from all rows , slice 1st-4th col :
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
